name: "✨ Feature Request"
description: "Suggest an idea for this project "
title: "Feat:"
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: "Describe the feature"
      description:
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Add ScreenShots"
      description: "Add sufficient SS to explain your issue."
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: "Record"
      options:
        - label: "I agree to follow this project's Code of Conduct"
          required: true
        - label: "I have starred the repository"
          required: true
        - label: "I'm a gssoc-24-extd contributor"
        - label: "I want to work on this issue"
